name: game_lists
description: The app for tracking what you're playing.
version: 1.16.0
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  image: ^3.0.2
  image_picker: ^0.7.4
  provider: ^5.0.0
  hive: ^2.0.2
  hive_flutter: ^1.0.0
  dio: ^4.0.0
  intl: ^0.17.0
  fl_chart: ^0.36.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.0.1
  build_runner: ^2.0.1
flutter:
  uses-material-design: true
  assets:
    - images/image.png
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
